### ISSUE TITLE
Hassio 0.115.2 invalid config

### ISSUE THREAD

**Issue by stackner** [JohNan/home-assistant-plaato#3] opened 2020-09-20 08:54 UTC
Invalid config
The following integrations and platforms could not be set up:

plaato.sensor
Please check your config.

**Comment by JohNan** [comment] 2020-09-20 15:59
Thank you. Duplicate of https://github.com/JohNan/home-assistant-plaato/issues/2

**Closed as completed by JohNan** 2020-09-20 15:59 UTC
